[package]
name = "rusticom"
version = "0.1.0"
authors = ["Marc Dietrichstein <marc@hero-workout.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
